version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ifconecta-db
    environment:
      POSTGRES_DB: ifconecta
      POSTGRES_USER: ${DB_USER:-ifconecta_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-local_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: ifconecta-mailhog
    ports:
      - "1025:1025" # Porta do SMTP
      - "8025:8025" # Porta da Interface Web

volumes:
  postgres_data: